### ISSUE TITLE
Elementor upgrade breaks Jumpstart theme v 1.11

### ISSUE THREAD

**Issue by neuharthr** [tommusrhodus/TommusRhodus-Framework#3]
Hi Tom. After upgrading to Elementor 3.6.5, I received the following error in the Jumpstart (v 1.0.10) (TommusRhodus Framework v 1.0.2) theme.
**Stack trace:**
```
[01-May-2022 22:06:59 UTC] PHP Fatal error:  Uncaught Error: Class 'Elementor\Scheme_Color' not found in /var/www/html/wp-content/plugins/TommusRhodus-Framework-master/elementor-blocks/jumpstart/counter-block.php:113
#0 /var/www/html/wp-content/plugins/elementor/includes/base/controls-stack.php(2280): Elementor\Widget_TommusRhodus_Counter_Block->_register_controls()
#1 /var/www/html/wp-content/plugins/elementor/includes/base/controls-stack.php(494): Elementor\Controls_Stack->init_controls()
#2 /var/www/html/wp-content/plugins/elementor/includes/base/widget-base.php(177): Elementor\Controls_Stack->get_stack()
#3 /var/www/html/wp-content/plugins/elementor/includes/base/controls-stack.php(300): Elementor\Widget_Base->get_stack()
#4 /var/www/html/wp-content/plugins/elementor/core/files/css/global-css.php(120): Elementor\Controls_Stack->get_controls()
#5 /var/www/html/wp-content/plugins/elementor/core/files/css/global-css.php(66): Elementor\Core\Files\CSS\Global_CSS->render_schemes_and_globals_css()
#6 /var/www/html/wp-content/plugins/elementor/ in /var/www/html/wp-content/plugins/TommusRhodus-Framework-master/elementor-blocks/jumpstart/counter-block.php on line 113

```
**The fix was found here:**
https://forum.elementor.com/fixing-common-issues-33/wordpress-error-with-elementor-plugin-10649
Wherever you see this error, you should replace Scheme_Color with \Elementor\Core\Schemes\Color
Like so:
```
'scheme' => [
                    //'type' => Scheme_Color::get_type(),
                    //'value' => Scheme_Color::COLOR_1,
                    'type' => \Elementor\Core\Schemes\Color::get_type(),
                    'value' => \Elementor\Core\Schemes\Color::COLOR_1,
                ],
```

**More details of the cause is here:**
https://github.com/elementor/elementor/issues/16159#issuecomment-1047723865

Can you incorporate this change and push out to the next release?

**Comment by tommusrhodus** [comment]
This was updated a few days ago https://github.com/tommusrhodus/TommusRhodus-Framework/commit/b84504b62c79291b883be2e2f7ab44092db7c801 👍 

Delete the plugin from your site, and let the theme re-install it from "appearance => install plugins", this will always give you the latest version.
